
# Theme Config

# Logo
logo_image_source: https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f530.svg

# Index Page
index_banner_text: Minato Note
index_banner_text_secondary: なんか適当に書いている
index_font_awesome_icon_css: fa fa-magic

# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  About: https://minato86.me/about.html
  Donation: https://ko-fi.com/minato86
  Contact: https://minato86.me/contact.html

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MMM YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: https://i.gyazo.com/f1474692c18a4db231034524dd85b794.jpg
about_widget_text: "こんにちは、インターネット老人です。プログラムと映像、デザインをしてます。詳細は上部のAboutへ"


# Comments.
comments:
  # Disqus comments
  disqus_shortname: minatonote

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
  - url: https://twitter.com/minatoo86
    fa_icon: fa-twitter
  - url: https://github.com/Chipsnet
    fa_icon: fa-github
  - url: https://minato86.me
    fa_icon: fa-home

# Footer about
footer_about: "©2020 Minami Minato"
